# Generated by Django 3.1.3 on 2021-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_estimates',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
