# Generated by Django 3.1.3 on 2021-01-31 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210128_1513'),
        ('users', '0002_auto_20210107_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['score']},
        ),
        migrations.AddField(
            model_name='profile',
            name='tracked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.question'),
        ),
    ]
