# Generated by Django 3.1.3 on 2021-01-11 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='forum',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.forum'),
            preserve_default=False,
        ),
    ]
