# Generated by Django 3.1.3 on 2021-01-31 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_auto_20210128_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tracked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
