# Generated by Django 3.1.3 on 2021-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
